---
- name: sssd_ldap | pamd | add pam_mkhomedir for Debian machines
  copy:
    src: pam_mkhomedir
    dest: /usr/share/pam-configs/sssd_mkhomedir
  when: ansible_os_family == "Debian"
  notify:
    - run pam auth update
