---
- name: sssd | configure sssd
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    backup: yes
    owner: root
    group: root
  notify:
    - restart sssd

- name: sssd | ensure sssd service is enabled
  service:
    name: sssd
    enabled: true
