---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: centos-7
    image: centos/systemd
    command: /usr/sbin/init
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0013
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
